import { User } from "@ourtypes/AppState";

export const dummyUsers: User[] = [
    {
        fullName: 'Alice Smith',
        email: 'alice.smith@example.com',
        major: 'Computer Science',
        password: 'password123',
        iD: 'e1e1e1e1-e1e1-e1e1-e1e1-e1e1e1e1e1e',
    },
    {
        fullName: 'Bob Johnson',
        email: 'bob.johnson@example.com',
        major: 'Software Engineering',
        password: 'password123',
        iD: 'f2f2f2f2-f2f2-f2f2-f2f2-f2f2f2f2f2f2',
    },
    {
        fullName: 'Charlie Brown',
        email: 'charlie.brown@example.com',
        major: 'Data Science',
        password: 'password123',
        iD: 'c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3',
    },
    {
        fullName: 'David Wilson',
        email: 'david.wilson@example.com',
        major: 'Information Technology',
        password: 'password123',
        iD: 'd4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4',
    },
    {
        fullName: 'Eva Green',
        email: 'eva.green@example.com',
        major: 'Cyber Security',
        password: 'password123',
        iD: 'e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5',
    },
    {
        fullName: 'Frank White',
        email: 'frank.white@example.com',
        major: 'Artificial Intelligence',
        password: 'password123',
        iD: 'f6f6f6f6-f6f6-f6f6-f6f6-f6f6f6f6f6f6',
    },
    {
        fullName: 'Grace Harris',
        email: 'grace.harris@example.com',
        major: 'Data Analytics',
        password: 'password123',
        iD: 'g7g7g7g7-g7g7-g7g7-g7g7-g7g7g7g7g7g7',
    },
    {
        fullName: 'Henry Ford',
        email: 'henry.ford@example.com',
        major: 'Computer Science',
        password: 'password123',
        iD: 'h8h8h8h8-h8h8-h8h8-h8h8-h8h8h8h8h8h8',
    },
    {
        fullName: 'Ivy Thomas',
        email: 'ivy.thomas@example.com',
        major: 'Web Development',
        password: 'password123',
        iD: 'i9i9i9i9-i9i9-i9i9-i9i9-i9i9i9i9i9i9',
    },
    {
        fullName: 'Jack Taylor',
        email: 'jack.taylor@example.com',
        major: 'Software Engineering',
        password: 'password123',
        iD: 'j0j0j0j0-j0j0-j0j0-j0j0-j0j0j0j0j0j0',
    },
    {
        fullName: 'Kate Evans',
        email: 'kate.evans@example.com',
        major: 'Data Science',
        password: 'password123',
        iD: 'k1k1k1k1-k1k1-k1k1-k1k1-k1k1k1k1k1k1',
    },
    {
        fullName: 'Liam Cooper',
        email: 'liam.cooper@example.com',
        major: 'Information Technology',
        password: 'password123',
        iD: 'l2l2l2l2-l2l2-l2l2-l2l2-l2l2l2l2l2l2',
    },
    {
        fullName: 'Mia Davis',
        email: 'mia.davis@example.com',
        major: 'Web Development',
        password: 'password123',
        iD: 'm3m3m3m3-m3m3-m3m3-m3m3-m3m3m3m3m3m3',
    },
    {
        fullName: 'Nathan Scott',
        email: 'nathan.scott@example.com',
        major: 'Data Analytics',
        password: 'password123',
        iD: 'n4n4n4n4-n4n4-n4n4-n4n4-n4n4n4n4n4n4',
    },
    {
        fullName: 'Olivia King',
        email: 'olivia.king@example.com',
        major: 'Cyber Security',
        password: 'password123',
        iD: 'o5o5o5o5-o5o5-o5o5-o5o5-o5o5o5o5o5o5',
    },
    {
        fullName: 'Paul Young',
        email: 'paul.young@example.com',
        major: 'Artificial Intelligence',
        password: 'password123',
        iD: 'p6p6p6p6-p6p6-p6p6-p6p6-p6p6p6p6p6p6',
    }
];
